config/routes.rb
Rails.application.routes.draw do
  get 'data_explorer/table_of_contents'
  get 'data_explorer/pie'
  get 'data_explorer/age'
  get 'data_explorer/access'
  get 'data_explorer/live'
  get 'data_explorer/comfortability'
  get 'data_explorer/usage'
  get 'data_explorer/lessons'
  get 'data_explorer/methods'
  get 'team_data/load' => 'team_data#load'

   devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
   resources :participants
   resources :uncomfortable_participants

#   root to: "participants#index"
    root to: "data_explorer#table_of_contents"  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/uncomfortable_participant.rb
class UncomfortableParticipant < ApplicationRecord
  belongs_to :participant
end

app/controllers/uncomfortable_participants_controller.rb
class UncomfortableParticipantsController < ApplicationController
  before_action :set_uncomfortable_participant, only: [:show, :edit, :update, :destroy]

  # GET /uncomfortable_participants
  # GET /uncomfortable_participants.json
  def index
    @uncomfortable_participants = UncomfortableParticipant.all
  end

  # GET /uncomfortable_participants/1
  # GET /uncomfortable_participants/1.json
  def show
  end

  # GET /uncomfortable_participants/new
  def new
    @uncomfortable_participant = UncomfortableParticipant.new
  end

  # GET /uncomfortable_participants/1/edit
  def edit
  end

  # POST /uncomfortable_participants
  # POST /uncomfortable_participants.json
  def create
    @uncomfortable_participant = UncomfortableParticipant.new(uncomfortable_participant_params)

    respond_to do |format|
      if @uncomfortable_participant.save
        format.html { redirect_to @uncomfortable_participant, notice: 'Uncomfortable participant was successfully created.' }
        format.json { render :show, status: :created, location: @uncomfortable_participant }
      else
        format.html { render :new }
        format.json { render json: @uncomfortable_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uncomfortable_participants/1
  # PATCH/PUT /uncomfortable_participants/1.json
  def update
    respond_to do |format|
      if @uncomfortable_participant.update(uncomfortable_participant_params)
        format.html { redirect_to @uncomfortable_participant, notice: 'Uncomfortable participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @uncomfortable_participant }
      else
        format.html { render :edit }
        format.json { render json: @uncomfortable_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uncomfortable_participants/1
  # DELETE /uncomfortable_participants/1.json
  def destroy
    @uncomfortable_participant.destroy
    respond_to do |format|
      format.html { redirect_to uncomfortable_participants_url, notice: 'Uncomfortable participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uncomfortable_participant
      @uncomfortable_participant = UncomfortableParticipant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uncomfortable_participant_params
      params.require(:uncomfortable_participant).permit(:participant_id, :skills_for_improvement, :first_skill, :reason_behind_first_skill)
    end
end

app/helpers/uncomfortable_participants_helper.rb
module UncomfortableParticipantsHelper
end

app/views/uncomfortable_participants/_form.html.erb
<%= form_with(model: uncomfortable_participant, local: true) do |form| %>
  <% if uncomfortable_participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uncomfortable_participant.errors.count, "error") %> prohibited this uncomfortable_participant from being saved:</h2>

      <ul>
      <% uncomfortable_participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :participant_id %>
    <%= form.text_field :participant_id, id: :uncomfortable_participant_participant_id %>
  </div>

  <div class="field">
    <%= form.label :skills_for_improvement %>
    <%= form.check_box :skills_for_improvement, id: :uncomfortable_participant_skills_for_improvement %>
  </div>

  <div class="field">
    <%= form.label :first_skill %>
    <%= form.text_area :first_skill, id: :uncomfortable_participant_first_skill %>
  </div>

  <div class="field">
    <%= form.label :reason_behind_first_skill %>
    <%= form.text_area :reason_behind_first_skill, id: :uncomfortable_participant_reason_behind_first_skill %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uncomfortable_participants/edit.html.erb
<h1>Editing Uncomfortable Participant</h1>

<%= render 'form', uncomfortable_participant: @uncomfortable_participant %>

<%= link_to 'Show', @uncomfortable_participant %> |
<%= link_to 'Back', uncomfortable_participants_path %>

app/views/uncomfortable_participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uncomfortable Participants</h1>

<table border="1", style="font-family:arial;font-size:12px;color:#000080">
  <thead>
    <tr>
      <th>Participant</th>
      <th>Skills For Improvement</th>
      <th>First Skill</th>
      <th>Reason Behind First Skill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uncomfortable_participants.each do |uncomfortable_participant| %>
      <tr>
        <td><%= uncomfortable_participant.skills_for_improvement %></td>
        <td><%= uncomfortable_participant.first_skill %></td>
        <td><%= uncomfortable_participant.reason_behind_first_skill %></td>
        <td><%= link_to 'Show', uncomfortable_participant %></td>
        <td><%= link_to 'Edit', edit_uncomfortable_participant_path(uncomfortable_participant) %></td>
        <td><%= link_to 'Destroy', uncomfortable_participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uncomfortable Participant', new_uncomfortable_participant_path %>

app/views/uncomfortable_participants/new.html.erb
<h1>New Uncomfortable Participant</h1>

<%= render 'form', uncomfortable_participant: @uncomfortable_participant %>

<%= link_to 'Back', uncomfortable_participants_path %>

app/views/uncomfortable_participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Participant:</strong>
  <%= @uncomfortable_participant.participant %>
</p>

<p>
  <strong>Skills for improvement:</strong>
  <%= @uncomfortable_participant.skills_for_improvement %>
</p>

<p>
  <strong>First skill:</strong>
  <%= @uncomfortable_participant.first_skill %>
</p>

<p>
  <strong>Reason behind first skill:</strong>
  <%= @uncomfortable_participant.reason_behind_first_skill %>
</p>

<%= link_to 'Edit', edit_uncomfortable_participant_path(@uncomfortable_participant) %> |
<%= link_to 'Back', uncomfortable_participants_path %>