config/routes.rb
Rails.application.routes.draw do
  get 'data_explorer/table_of_contents'
  get 'data_explorer/pie'
  get 'data_explorer/age'
  get 'data_explorer/access'
  get 'data_explorer/live'
  get 'data_explorer/comfortability'
  get 'data_explorer/usage'
  get 'data_explorer/lessons'
  get 'data_explorer/methods'
  get 'team_data/load' => 'team_data#load'

   devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
   resources :participants
   resources :uncomfortable_participants

#   root to: "participants#index"
    root to: "data_explorer#table_of_contents"  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participant.rb
class Participant < ApplicationRecord
    has_one :uncomfortable_participant
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:live_in_korea, :age, :have_internet_access, :usage_frequency, :reason_for_using, :comfortability, :lessons_taken, :benefitted_how, :activity_list)
    end 
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :live_in_korea %>
    <%= form.check_box :live_in_korea, id: :participant_live_in_korea %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :participant_age %>
  </div>

  <div class="field">
    <%= form.label :have_internet_access %>
    <%= form.check_box :have_internet_access, id: :participant_have_internet_access %>
  </div>

  <div class="field">
    <%= form.label :usage_frequency %>
    <%= form.number_field :usage_frequency, id: :participant_usage_frequency %>
  </div>

  <div class="field">
    <%= form.label :reason_for_using %>
    <%= form.text_area :reason_for_using, id: :participant_reason_for_using %>
  </div>

  <div class="field">
    <%= form.label :comfortability %>
    <%= form.check_box :comfortability, id: :participant_comfortability %>
  </div>

  <div class="field">
    <%= form.label :lessons_taken %>
    <%= form.check_box :lessons_taken, id: :participant_lessons_taken %>
  </div>

  <div class="field">
    <%= form.label :benefitted_how %>
    <%= form.text_area :benefitted_how, id: :participant_benefitted_how %>
  </div>

  <div class="field">
    <%= form.label :activity_list %>
    <%= form.text_area :activity_list, id: :participant_activity_list %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table border="1" style="font-family:arial;font-size:12px;color:#000080">
  <thead>
    <tr>
      <th>Live in Korea</th>
      <th>Age</th>
      <th>Have Internet Access</th>
      <th>Usage Frequency</th>
      <th>Reason For Using</th>
      <th>Comfortability</th>
      <th>Lessons Taken</th>
      <th>Benefitted How</th>
      <th>Activity List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.live_in_korea %></td>
        <td><%= participant.age %></td>
        <td><%= participant.have_internet_access %></td>
        <td><%= participant.usage_frequency %></td>
        <td><%= participant.reason_for_using %></td>
        <td><%= participant.comfortability %></td>
        <td><%= participant.lessons_taken %></td>
        <td><%= participant.benefitted_how %></td>
        <td><%= participant.activity_list %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Live in korea:</strong>
  <%= @participant.live_in_korea %>
</p>

<p>
  <strong>Age:</strong>
  <%= @participant.age %>
</p>

<p>
  <strong>Have internet access:</strong>
  <%= @participant.have_internet_access %>
</p>

<p>
  <strong>Usage frequency:</strong>
  <%= @participant.usage_frequency %>
</p>

<p>
  <strong>Reason for using:</strong>
  <%= @participant.reason_for_using %>
</p>

<p>
  <strong>Comfortability:</strong>
  <%= @participant.comfortability %>
</p>

<p>
  <strong>Lessons taken:</strong>
  <%= @participant.lessons_taken %>
</p>

<p>
  <strong>Benefitted how:</strong>
  <%= @participant.benefitted_how %>
</p>

<p>
  <strong>Activity list:</strong>
  <%= @participant.activity_list %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>